name: RSpec Tests

on: [pull_request]

jobs:
  verify:
    name:  Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Testing with React Testing Library
      run: |
        script/test
